### ISSUE TITLE
6.1 Examine errors when starting

### ISSUE THREAD

**Issue by tomfulton** [sitereactor/umbraco-console-example#1]
Just a heads up - if you try this example with a 6.1 installation, you get an Examine type initializer error (below).  The fix is to copy your `/config/` directory into `/bin/Debug/`.

Not sure exactly why it needs this, but I'm guessing its because of this line in the web.config that changed in 6.1:

6.0.3
`<section name="ExamineLuceneIndexSets" type="UmbracoExamine.Config.ExamineLuceneIndexes, UmbracoExamine" requirePermission="false" />`

6.1-beta:
`<section name="ExamineLuceneIndexSets" type="Examine.LuceneEngine.Config.IndexSets, Examine" requirePermission="false" />`

Is this an Umbraco/Examine issue?  I can post it on the issue tracker, just wasn't sure.

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Examine.ExamineManager' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Examine.Config.ExamineSettings' threw an exception. ---> System.Configuration.Configur
ationErrorsException: Unable to open configSource file 'config\ExamineSettings.config'. (D:\dev\path-to-project\bin\Debug\MyApp.exe.Config line 29)
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at Examine.Config.ExamineSettings..cctor()
   --- End of inner exception stack trace ---
   at Examine.Config.ExamineSettings.get_Instance()
   at Examine.ExamineManager.LoadProviders()
   at Examine.ExamineManager..ctor()
   at Examine.ExamineManager..cctor()
   --- End of inner exception stack trace ---
   at Examine.ExamineManager.get_Instance()
   at Umbraco.Web.Search.ExamineEvents.ApplicationStarted(UmbracoApplicationBase httpApplication, ApplicationContext applicationContext)
   at Umbraco.Core.ApplicationEventHandler.OnApplicationStarted(UmbracoApplicationBase umbracoApplication, ApplicationContext applicationContext)
   at Umbraco.Core.CoreBootManager.<Complete>b__5(IApplicationEventHandler x)
   at Umbraco.Core.EnumerableExtensions.ForEach[TItem](IEnumerable`1 items, Action`1 action)
   at Umbraco.Core.CoreBootManager.Complete(Action`1 afterComplete)
   at Umbraco.Core.UmbracoApplicationBase.StartApplication(Object sender, EventArgs e)
   at Umbraco.Core.UmbracoApplicationBase.Application_Start(Object sender, EventArgs e)
   at MyApp.ConsoleApplicationBase.Start(Object sender, EventArgs e) in D:\dev\path-to-project\ConsoleApplicationBase.cs:line 22
   at MyApp.Program.Main(String[] args) in D:\dev\path-to-project\Program.cs:line 22
```

Also a bit strange, Examine creates a folder called "~" and creates an App_Data folder underneath instead of using the App_Data that already gets created for the log.

**Comment by sitereactor** [comment]
I have also encountered this issue in later versions of Umbraco. Well, since 6.1 like you. Since Examine was included in the Core. I haven't found out why this event is failing, but simply removing it from the startup process will remove the error. 
Will update the sample with a new Application- and BootManager that includes the possibility of removing events from the startup process.

**Comment by CGaskell** [comment]
Hey Morten,

Did you add anything in for this? I'm seeing the error on first request after a clean deployment.

Cheers,

Chris

**Comment by sitereactor** [comment]
Sorry for not getting back to this.
The ServiceContextManager found here https://github.com/umbraco/Umbraco-CMS/blob/7.0.3/src/Umbraco.Core/Standalone/ServiceContextManager.cs has an example of how to remove the examine event handlers from the CoreBootManager.

Btw. the repo is updated with an umbraco 7 version of the console example.
